version: '3.8'
#  agar shu yerni ozida image qidirmoqchi bolsayizla Ctrl+  space 2x
services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bexa
      POSTGRES_DB: kpi_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - kpisystem-net
  app:
    build: .
    container_name: kpi-system
    ports:
      - "7777:7777"
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/kpi_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: bexa
    networks:
      - kpisystem-net
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis_data:/data
    networks:
      - kpisystem-net

  redis-commander:
    image: rediscommander/redis-commander:latest
    platform: linux/amd64
    container_name: redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=12345
    depends_on:
      - redis
    networks:
      - kpisystem-net

volumes:
  redis_data:
  pg_data:

networks:
  kpisystem-net:
    driver: bridge