spring.application.name=kpi-system
server.port=7777
spring.sql.init.platform=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/kpi_db
spring.datasource.username=postgres
spring.datasource.password=bexa
spring.jpa.hibernate.ddl-auto=update
jwt.token.secret=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b